name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Remove existing virtual environment
      run: |
        if [ -d ".venv" ]; then rm -rf .venv; fi

    - name: Install virtualenv
      run: |
        pip install virtualenv

    - name: Install dependencies
      run: |
        virtualenv .venv
        . .venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . .venv/bin/activate
        python -m unittest discover -s tests -v

    - name: Start Flask app
      run: |
        . .venv/bin/activate
        nohup python mypython.py &> flask.log &

    - name: Wait for Flask to start
      run: sleep 20

    - name: Check Flask logs
      run: |
        cat flask.log

    - name: Test Flask app
      run: |
        curl -f http://localhost:5001/

    - name: Stop Flask app
      run: |
        pkill -f "python mypython.py"

  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # List repository files to confirm structure and file presence
      - name: List repository files
        run: ls -R

      # Perform the GenAI Code Review
      - name: GenAI Code Review
        uses: <correct-action-repo>@<version>
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.pull_request.number }} # Ensure correct PR ID
          openai_model: "gpt-3.5-turbo" # Optional
          openai_temperature: 0.5 # Optional
          openai_max_tokens: 2048 # Optional
          mode: files # 'files' or 'patch'
          language: en # Optional, default is 'en'
          custom_prompt: "" # Optional
