name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Remove existing virtual environment
      run: |
        if [ -d ".venv" ]; then rm -rf .venv; fi

    - name: Install virtualenv
      run: |
        pip install virtualenv

    - name: Install dependencies
      run: |
        virtualenv .venv
        . .venv/bin/activate
        pip install openai==0.28

    - name: Run tests
      run: |
        . .venv/bin/activate
        python -m unittest discover -s tests -v

    - name: Start Flask app
      run: |
        . .venv/bin/activate
        nohup python mypython.py &> flask.log &

    - name: Wait for Flask to start
      run: sleep 20

    - name: Check Flask logs
      run: |
        cat flask.log

    - name: Test Flask app
      run: |
        curl -f http://localhost:5001/

    - name: Stop Flask app
      run: |
        pkill -f "python mypython.py"

  code_review_job:
    runs-on: ubuntu-latest
    name: AI Code Review
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28

      - name: List repository files
        run: ls -R

      - name: Run AI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python ai_code_review.py
